package kz.paysoft.paymobile.ui.pmclient.model.views;

import kz.paysoft.paymobile.ui.pmclient.model.entities.ApplicationImpl;
import kz.paysoft.paymobile.ui.pmclient.model.views.common.ApplicationsViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 08 17:56:37 BDST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApplicationsViewRowImpl extends ViewRowImpl implements ApplicationsViewRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getId();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        Status {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        AppliedAt {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getAppliedAt();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setAppliedAt((Date)value);
            }
        }
        ,
        CountryId {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getCountryId();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setCountryId((Number)value);
            }
        }
        ,
        DocTypeId {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getDocTypeId();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setDocTypeId((Number)value);
            }
        }
        ,
        DocId {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getDocId();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setDocId((String)value);
            }
        }
        ,
        PhoneNumber {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getPhoneNumber();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setPhoneNumber((Number)value);
            }
        }
        ,
        BranchId {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getBranchId();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setBranchId((Number)value);
            }
        }
        ,
        Manager {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getManager();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setManager((String)value);
            }
        }
        ,
        ManagerDate {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getManagerDate();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setManagerDate((Date)value);
            }
        }
        ,
        LastName {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getLastName();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setLastName((String)value);
            }
        }
        ,
        FirstName {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getFirstName();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setFirstName((String)value);
            }
        }
        ,
        BirthDate {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getBirthDate();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setBirthDate((Date)value);
            }
        }
        ,
        DocDate {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getDocDate();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setDocDate((Date)value);
            }
        }
        ,
        DocIssuer {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getDocIssuer();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setDocIssuer((String)value);
            }
        }
        ,
        Address {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getAddress();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setAddress((String)value);
            }
        }
        ,
        MiddleName {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getMiddleName();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setMiddleName((String)value);
            }
        }
        ,
        TaxPayerId {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getTaxPayerId();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setTaxPayerId((String)value);
            }
        }
        ,
        DeclineReason {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getDeclineReason();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setDeclineReason((String)value);
            }
        }
        ,
        CipherSuite {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getCipherSuite();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setCipherSuite((String)value);
            }
        }
        ,
        AppAccountsView {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getAppAccountsView();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ApplicationStatus {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getApplicationStatus();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Branches {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getBranches();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Countries {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getCountries();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DocTypes {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getDocTypes();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Users {
            public Object get(ApplicationsViewRowImpl obj) {
                return obj.getUsers();
            }

            public void put(ApplicationsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ApplicationsViewRowImpl object);

        public abstract void put(ApplicationsViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int APPLIEDAT = AttributesEnum.AppliedAt.index();
    public static final int COUNTRYID = AttributesEnum.CountryId.index();
    public static final int DOCTYPEID = AttributesEnum.DocTypeId.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int PHONENUMBER = AttributesEnum.PhoneNumber.index();
    public static final int BRANCHID = AttributesEnum.BranchId.index();
    public static final int MANAGER = AttributesEnum.Manager.index();
    public static final int MANAGERDATE = AttributesEnum.ManagerDate.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int BIRTHDATE = AttributesEnum.BirthDate.index();
    public static final int DOCDATE = AttributesEnum.DocDate.index();
    public static final int DOCISSUER = AttributesEnum.DocIssuer.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int MIDDLENAME = AttributesEnum.MiddleName.index();
    public static final int TAXPAYERID = AttributesEnum.TaxPayerId.index();
    public static final int DECLINEREASON = AttributesEnum.DeclineReason.index();
    public static final int CIPHERSUITE = AttributesEnum.CipherSuite.index();
    public static final int APPACCOUNTSVIEW = AttributesEnum.AppAccountsView.index();
    public static final int APPLICATIONSTATUS = AttributesEnum.ApplicationStatus.index();
    public static final int BRANCHES = AttributesEnum.Branches.index();
    public static final int COUNTRIES = AttributesEnum.Countries.index();
    public static final int DOCTYPES = AttributesEnum.DocTypes.index();
    public static final int USERS = AttributesEnum.Users.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ApplicationsViewRowImpl() {
    }

    public void prepareToDecline() {
        setStatus("D");
    }

    /**
     * Gets Application entity object.
     * @return the Application
     */
    public ApplicationImpl getApplication() {
        return (ApplicationImpl)getEntity(0);
    }


    /**
     * Gets the attribute value for ID$ using the alias name Id.
     * @return the ID$
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID$ using the alias name Id.
     * @param value value to set the ID$
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for APPLIED_AT using the alias name AppliedAt.
     * @return the APPLIED_AT
     */
    public Date getAppliedAt() {
        return (Date)getAttributeInternal(APPLIEDAT);
    }

    /**
     * Sets <code>value</code> as attribute value for APPLIED_AT using the alias name AppliedAt.
     * @param value value to set the APPLIED_AT
     */
    public void setAppliedAt(Date value) {
        setAttributeInternal(APPLIEDAT, value);
    }

    /**
     * Gets the attribute value for COUNTRY_ID$ using the alias name CountryId.
     * @return the COUNTRY_ID$
     */
    public Number getCountryId() {
        return (Number)getAttributeInternal(COUNTRYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_ID$ using the alias name CountryId.
     * @param value value to set the COUNTRY_ID$
     */
    public void setCountryId(Number value) {
        setAttributeInternal(COUNTRYID, value);
    }

    /**
     * Gets the attribute value for DOC_TYPE_ID$ using the alias name DocTypeId.
     * @return the DOC_TYPE_ID$
     */
    public Number getDocTypeId() {
        return (Number)getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_TYPE_ID$ using the alias name DocTypeId.
     * @param value value to set the DOC_TYPE_ID$
     */
    public void setDocTypeId(Number value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for DOC_ID using the alias name DocId.
     * @return the DOC_ID
     */
    public String getDocId() {
        return (String)getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId.
     * @param value value to set the DOC_ID
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     * @return the PHONE_NUMBER
     */
    public Number getPhoneNumber() {
        return (Number)getAttributeInternal(PHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     * @param value value to set the PHONE_NUMBER
     */
    public void setPhoneNumber(Number value) {
        setAttributeInternal(PHONENUMBER, value);
    }

    /**
     * Gets the attribute value for BRANCH_ID$ using the alias name BranchId.
     * @return the BRANCH_ID$
     */
    public Number getBranchId() {
        return (Number)getAttributeInternal(BRANCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH_ID$ using the alias name BranchId.
     * @param value value to set the BRANCH_ID$
     */
    public void setBranchId(Number value) {
        setAttributeInternal(BRANCHID, value);
    }


    /**
     * Gets the attribute value for MANAGER using the alias name Manager.
     * @return the MANAGER
     */
    public String getManager() {
        return (String) getAttributeInternal(MANAGER);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER using the alias name Manager.
     * @param value value to set the MANAGER
     */
    public void setManager(String value) {
        setAttributeInternal(MANAGER, value);
    }

    /**
     * Gets the attribute value for MANAGER_DATE using the alias name ManagerDate.
     * @return the MANAGER_DATE
     */
    public Date getManagerDate() {
        return (Date)getAttributeInternal(MANAGERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_DATE using the alias name ManagerDate.
     * @param value value to set the MANAGER_DATE
     */
    public void setManagerDate(Date value) {
        setAttributeInternal(MANAGERDATE, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String)getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String)getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for BIRTH_DATE using the alias name BirthDate.
     * @return the BIRTH_DATE
     */
    public Date getBirthDate() {
        return (Date)getAttributeInternal(BIRTHDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BIRTH_DATE using the alias name BirthDate.
     * @param value value to set the BIRTH_DATE
     */
    public void setBirthDate(Date value) {
        setAttributeInternal(BIRTHDATE, value);
    }

    /**
     * Gets the attribute value for DOC_DATE using the alias name DocDate.
     * @return the DOC_DATE
     */
    public Date getDocDate() {
        return (Date)getAttributeInternal(DOCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_DATE using the alias name DocDate.
     * @param value value to set the DOC_DATE
     */
    public void setDocDate(Date value) {
        setAttributeInternal(DOCDATE, value);
    }

    /**
     * Gets the attribute value for DOC_ISSUER using the alias name DocIssuer.
     * @return the DOC_ISSUER
     */
    public String getDocIssuer() {
        return (String)getAttributeInternal(DOCISSUER);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ISSUER using the alias name DocIssuer.
     * @param value value to set the DOC_ISSUER
     */
    public void setDocIssuer(String value) {
        setAttributeInternal(DOCISSUER, value);
    }

    /**
     * Gets the attribute value for ADDRESS using the alias name Address.
     * @return the ADDRESS
     */
    public String getAddress() {
        return (String)getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS using the alias name Address.
     * @param value value to set the ADDRESS
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for MIDDLE_NAME using the alias name MiddleName.
     * @return the MIDDLE_NAME
     */
    public String getMiddleName() {
        return (String)getAttributeInternal(MIDDLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MIDDLE_NAME using the alias name MiddleName.
     * @param value value to set the MIDDLE_NAME
     */
    public void setMiddleName(String value) {
        setAttributeInternal(MIDDLENAME, value);
    }

    /**
     * Gets the attribute value for TAX_PAYER_ID using the alias name TaxPayerId.
     * @return the TAX_PAYER_ID
     */
    public String getTaxPayerId() {
        return (String)getAttributeInternal(TAXPAYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_PAYER_ID using the alias name TaxPayerId.
     * @param value value to set the TAX_PAYER_ID
     */
    public void setTaxPayerId(String value) {
        setAttributeInternal(TAXPAYERID, value);
    }

    /**
     * Gets the attribute value for DECLINE_REASON using the alias name DeclineReason.
     * @return the DECLINE_REASON
     */
    public String getDeclineReason() {
        return (String)getAttributeInternal(DECLINEREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for DECLINE_REASON using the alias name DeclineReason.
     * @param value value to set the DECLINE_REASON
     */
    public void setDeclineReason(String value) {
        setAttributeInternal(DECLINEREASON, value);
    }


    /**
     * Gets the attribute value for CIPHER_SUITE using the alias name CipherSuite.
     * @return the CIPHER_SUITE
     */
    public String getCipherSuite() {
        return (String) getAttributeInternal(CIPHERSUITE);
    }

    /**
     * Sets <code>value</code> as attribute value for CIPHER_SUITE using the alias name CipherSuite.
     * @param value value to set the CIPHER_SUITE
     */
    public void setCipherSuite(String value) {
        setAttributeInternal(CIPHERSUITE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AppAccountsView.
     */
    public RowIterator getAppAccountsView() {
        return (RowIterator)getAttributeInternal(APPACCOUNTSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ApplicationStatus.
     */
    public RowSet getApplicationStatus() {
        return (RowSet)getAttributeInternal(APPLICATIONSTATUS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Branches.
     */
    public RowSet getBranches() {
        return (RowSet)getAttributeInternal(BRANCHES);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Countries.
     */
    public RowSet getCountries() {
        return (RowSet)getAttributeInternal(COUNTRIES);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DocTypes.
     */
    public RowSet getDocTypes() {
        return (RowSet)getAttributeInternal(DOCTYPES);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Users.
     */
    public RowSet getUsers() {
        return (RowSet)getAttributeInternal(USERS);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
