package kz.paysoft.paymobile.ui.setup.model.entities;

import kz.paysoft.paymobile.ui.adfextensions.ExtendedEntityImpl;
import kz.paysoft.paymobile.ui.setup.model.MessageBundle;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 03 17:55:57 BDST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StatusDetailImpl extends ExtendedEntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * This is the default constructor (do not remove).
     */
    public StatusDetailImpl() {
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("kz.paysoft.paymobile.ui.setup.model.entities.StatusDetail");
        }
        return mDefinitionObject;
    }


    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        //super.create(attributeList);
        throw new JboException(MessageBundle.class, MessageBundle.OPERATION_IS_DISALLOWED, null);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        //super.remove();
        throw new JboException(MessageBundle.class, MessageBundle.OPERATION_IS_DISALLOWED, null);
    }
}
