package kz.paysoft.paymobile.ui.pmclient.model.client;

import kz.paysoft.paymobile.ui.pmclient.model.common.PMClientService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 08 19:17:13 BDST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PMClientServiceClient extends ApplicationModuleImpl implements PMClientService {
    /**
     * This is the default constructor (do not remove).
     */
    public PMClientServiceClient() {
    }


    public void getClientAndContract() {
        Object _ret = this.riInvokeExportedMethod(this,"getClientAndContract",null,null);
        return;
    }

    public String getCurrentAppStatus() {
        Object _ret = this.riInvokeExportedMethod(this,"getCurrentAppStatus",null,null);
        return (String)_ret;
    }

    public void activateContractAndNotify() {
        Object _ret = this.riInvokeExportedMethod(this,"activateContractAndNotify",null,null);
        return;
    }

    public void activateContract() {
        Object _ret = this.riInvokeExportedMethod(this,"activateContract",null,null);
        return;
    }
}
