package kz.paysoft.paymobile.ui.pmclient.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 08 17:58:09 BDST 2010
// ---------------------------------------------------------------------
public interface ApplicationsViewRow extends Row {
    void prepareToDecline();
}
