package kz.paysoft.paymobile.ui.pmclient.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 12 19:15:48 BDST 2010
// ---------------------------------------------------------------------
public interface ContractsViewRow extends Row {
    void check();

    void close();

    void resetPasswordTries();
}
