package kz.paysoft.paymobile.ui.pmclient.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 08 19:17:13 BDST 2010
// ---------------------------------------------------------------------
public interface PMClientService extends ApplicationModule {
    void getClientAndContract();

    String getCurrentAppStatus();

    void activateContractAndNotify();

    void activateContract();
}
