package kz.paysoft.paymobile.ui.pmclient.model.views.client;

import kz.paysoft.paymobile.ui.pmclient.model.views.common.ContractsViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 12 19:15:48 BDST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractsViewRowClient extends RowImpl implements ContractsViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public ContractsViewRowClient() {
    }

    public void check() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"check",null,null);
        return;
    }

    public void close() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"close",null,null);
        return;
    }

    public void resetPasswordTries() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"resetPasswordTries",null,null);
        return;
    }
}
